name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}
    - name: Publish to Registry
      uses: Asimmetric/Publish-Docker-Github-Action@${{ github.ref }}
      with:
        name: uxi/publish-docker-github-action
        registry: quay.io
        username: ${{ secrets.QUAY_UXI_ROBOT_USER }}
        password: ${{ secrets.QUAY_UXI_ROBOT_PWD }}
        tags: "latest,integration-test,temp"
        check_existing: true
        tag_names: true
